apiVersion: networking.k8s.io/v1beta1
kind: TrafficSplit
metadata:
  name: myapp-split
spec:
  service: myapp-service
  backends:
  - serviceName: myapp-v1
    weight: 50
  - serviceName: myapp-v2
    weight: 50
